environment = "dev"
location    = "South India"
resource_group_name  = "todo-app"
storage_account_name = "tododevtf"
container_name       = "tfstate"
key                  = "terraform.tfstate"
client_id            = "381b4cbe-2228-4762-9083-d58b7a7e1c19"
client_secret        = "5Ax8Q~5mHwFqPPoqvxIR4qr95WftsC6ZwDmExc4F"